apiVersion: v1
kind: Service
metadata:
  name: myapp-frontend-service
  namespace: employee
spec:
  selector:
    type: myapp-frontend
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-frontend-deployment
  namespace: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      type: myapp-frontend
  template:
    metadata:
      labels:
        type: myapp-frontend
    spec:
      containers:
      - name: myapp-frontend-container
        image: mymongoapp1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"        
        imagePullPolicy: IfNotPresent
      
        ports:
        - containerPort: 5000