apiVersion: v1
kind: Service
metadata:
  name: mongo-back-service1
  
  labels:
    type: mongo-backend
spec:
  ports:
  - name: mongo-port
    port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    type: mongo-backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-back-deployment

spec:
  selector:
    matchLabels:
      type: mongo-backend
  serviceName: "mongo-back-deployment"
  replicas: 1
  template:
    metadata:
      labels:
        type: mongo-backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo-back-container
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi